### ISSUE TITLE
Cannot read property 'ldBar' of null

### ISSUE THREAD

**Issue by ratacat** [loadingio/loading-bar#30]
Trying to get this running on a dead basic html file in most recent version of chrome...and not all the time, but sometimes I am seeing this error.  Anyone have any ideas what might be causing it?

It's when I try and instantiate with this command `b = new ldBar('h3 .lDbar')`

```
loading-bar.ls:95 Uncaught TypeError: Cannot read property 'ldBar' of null
    at new ldBar (loading-bar.ls:95)
    at <anonymous>:1:5
```

here is my html file
```
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/assets/loadingbar.css"/>
        <script type="text/javascript" src="/assets/loadingbar.js"></script>
    </head>
    <body>
        <h3 class="ldBar" data-preset="text" data-value="35">This is the bar.</h3>
    </body>
</html>
```

**Comment by zbryikt** [comment]
Hi ratacat, I think it's because the selector is not matched with your ldBar element.

You type:

    h3 .lDbar

instead it should be:

    h3.ldBar

there should be no space between ```h3``` and ```.ldBar```, and css selector is case sensitive so it should be ```.ldBar``` instead of ```.lDbar```.

[here](https://codepen.io/loadingio/pen/XLGLgQ) is an example for both case.
